# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f567a4a3bcefe1b3e3c5833ad754d4ca002d3c4c11ab8514f6a5cb3f39919333be62b68a2333e1c9eba217ffa1a01ec0b183d05a5ef74b7ae6ca0e7981c51771

test:
  secret_key_base: 4efab787529e39c26e11fec06a62c26df66171c5bfa2f4b102dc7bf52ee48bad21b7d08f2cae9b5b303a45307ac4bce1b1dca1c39613670c1296f526897b14f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
